# Generated by Django 4.2.5 on 2023-10-03 14:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='profiles/')),
                ('bio', models.TextField()),
                ('jinsi', models.CharField(choices=[('Erkak', 'Erkak'), ('Ayol', 'Ayol')], max_length=100)),
                ('ages', models.IntegerField()),
                ('numberphone', models.IntegerField(default='998')),
                ('user', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='img/')),
                ('vaqti', models.CharField(default=datetime.date.today, max_length=200)),
                ('user', models.CharField(max_length=200)),
                ('categ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.category')),
            ],
        ),
    ]
